name = "crm-web"
compatibility_date = "2026-08-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist/client"

[vars]
VITE_API_URL = "https://api.seanleejh.com"

[env.preview]
name = "crm-web-preview"
pages_build_output_dir = "dist/client"

[env.preview.vars]
VITE_API_URL = "https://ember-api-preview.seanleejh.workers.dev"

[env.production]
name = "crm-web"
pages_build_output_dir = "dist/client"

[env.production.vars]
VITE_API_URL = "https://api.seanleejh.com"
